### ISSUE TITLE
播放组件有问题

### ISSUE THREAD

**Issue by SGL647** [Adicwu/comic-pc#1]
按照源码里的模拟数据，模拟了后端接口，发现播放有问题，video标签被覆盖了，选集也没有
![捕获](https://user-images.githubusercontent.com/61075731/172416513-2f548c66-25e6-4d4c-9369-cbea0cfcb9c5.PNG)

**Comment by Adicwu** [comment]
老的假数据失效了，已修改

**Comment by Adicwu** [comment]
已完成
